TEST_INPUTS = {
    "calculator": "calculate 5 plus 7",
    "brightness_windows": "brightness up",
    "clipboard": "clipboard read",
    "clipboard_history": "clipboard history",
    "converter": "convert 5 miles to kilometers",
    "date": "what is today's date",
    "dictionary": "define entropy",
    "greet": "hello",
    "ip_address_windows": "ip address",
    "jokes": "tell me a joke",
    "media_control_windows": "volume up",
    "news": "news",
    "note_windows": "take a note: buy milk",
    "open_browser_windows": "open browser",
    "pause": "pause",
    "pc_commands_windows": "shutdown",
    "recycle_bin_windows": "empty recycle bin",
    "reminder": "remind me in 5 minutes",
    "screenshot_windows": "take a screenshot",
    "stopwatch": "start stopwatch",
    "system_info_windows": "system info",
    "test_imports": "test imports",
    "time": "what time is it",
    "timer": "set a timer for 10 seconds",
    "top_processes_windows": "top processes",
    "weather": "weather in Indianapolis",
    "wifi_info_windows": "wifi info",
    "wikipedia": "wikipedia Albert Einstein",
    "youtube": "open youtube",
}
